---
swagger: "2.0"
info:
  description: "Task Manager API"
  title: "Task Manager API"
  version: "0.0.1"
host: "localhost:10001"
schemes:
- "https"
- "http"
basePath: "/api/v0"
securityDefinitions:
  apiKeyAuth:
    type: "apiKey"
    name: "X-Auth-Key"
    in: "header"
tags:
  $ref: "tags.yaml#/tags"
paths:
  $ref: "paths.yaml"
definitions:
  $ref: "definitions.yaml"  
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
