---
swagger: "2.0"
info:
  description: "Task Manager API"
  title: "Task Manager API"
  version: "0.0.1"
host: "localhost:10001"
schemes:
- "https"
- "http"
basePath: "/api/v0"
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
  apiKeyAuth:
    type: "apiKey"
    name: "X-Auth-Key"
    in: "header"
tags:
- $ref: "task/base.yaml#/tags"
- $ref: "pet/base.yaml#/tags"
- $ref: "store/base.yaml#/tags"
- $ref: "user/base.yaml#/tags"
paths:
  $ref: "paths.yaml"
definitions:
  $ref: "definitions.yaml"  
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
